### ISSUE TITLE
When saving project data with boundary condition with iRIC v4 beta built with AppVeyor, saving boundary condition fails

### ISSUE THREAD

**Issue by kskinoue0612** [i-RIC/online_update#32]
When saving project data with boundary condition with iRIC v4 beta built with AppVeyor, saving boundary condition fails. Only partial data is saved.

Please test with issue-32.zip attach to this:
1. Open project
2. Create grid, and map inflow1, inflow2 to grid
3. Save project

Then, only inflow1 is saved to CGNS file.

[issue-32.zip](https://github.com/i-RIC/online_update/files/7289893/issue-32.zip)

**Comment by scharlton2** [comment]
Hi Keiskuke,

I don't have the v4 version of naysflood.  Could you attach it here?

Thanks,
Scott

**Comment by kskinoue0612** [comment]
Hi Scott,

Thank you for your contact.
I'm sorry, I forgot to close this one, actually this issue is already closed.
Please refer to https://github.com/i-RIC/prepost-gui/issues/985.

Thank you,

Keisuke Inoue
