### ISSUE TITLE
During installation of runtimes the computer occasionally reboots

### ISSUE THREAD

**Issue by scharlton2** [i-RIC/online_update#6]
This seems to occur when an older runtime (such as 12.0.30501.0 for VS2013) is in use (by some other program) during the install and the iRIC installer attempts to install a newer version (such as 12.0.40660.0). The /q or /quiet option suppresses all notifications and will restart the computer whenever necessary see:

https://docs.microsoft.com/en-us/windows/desktop/msi/standard-installer-command-line-options

To demonstrate the problem:

1. On a test machine (such as a virtual machine) uninstall all Microsoft Visual C++ 2013 Redistributable (x64) installations.

2. Copy [vs2013_x64.exe](https://github.com/scharlton2/online_update/files/3105360/VS2013_x64.zip) to test machine

3. Verify [vs2013_x64.exe](https://github.com/scharlton2/online_update/files/3105360/VS2013_x64.zip) can't run without MSVCR120.DLL.

4. Install [vcredist_x64.exe](https://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x64.exe) (Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.30501)

5. Verify [vs2013_x64.exe](https://github.com/scharlton2/online_update/files/3105360/VS2013_x64.zip) can now run.

6. While [vs2013_x64.exe](https://github.com/scharlton2/online_update/files/3105360/VS2013_x64.zip) is running, install [vcredist_x64.exe](http://download.microsoft.com/download/0/5/6/056dcda9-d667-4e27-8001-8a0c6971d6b1/vcredist_x64.exe) (Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.40660)
from a command line using the /q switch. (ie `C:\Users\Public\vcredist_x64.exe /q`)

7. Machine should reboot.

To verify fix:
1. Repeat steps 1 - 5

2. While [vs2013_x64.exe](https://github.com/scharlton2/online_update/files/3105360/VS2013_x64.zip) is running, install [vcredist_x64.exe](http://download.microsoft.com/download/0/5/6/056dcda9-d667-4e27-8001-8a0c6971d6b1/vcredist_x64.exe) (Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.40660)
from a command line using the /quiet and /norestart switches. (ie `C:\Users\Public\vcredist_x64.exe /quiet /norestart`)  
(NOTE: This step can be done using powershell to verify the return code: [ERROR_SUCCESS_REBOOT_REQUIRED](https://docs.microsoft.com/en-us/windows/desktop/Msi/error-codes) (3010))
```
PS C:\Users\user> $p = Start-Process C:\Users\Public\vcredist_x64.exe -ArgumentList "/quiet /norestart" -wait -NoNewWindow -PassThru
PS C:\Users\user> $p.ExitCode
```

3. Machine shouldn't reboot.

**Comment by kskinoue0612** [comment]
Hi Scott,

Thanks for this information.

It seems that it will take some time to reproduce the issue. Maybe I will
setup a virtual environment to test this. When I’ve tested, I’ll contact
you.

Thanks,

Keisuke


2019年4月23日(火) 10:41 Scott Charlton <notifications@github.com>:
